// RobotBuilder Version: 2.0
//
// This file was generated by RobotBuilder. It contains sections of
// code that are automatically generated and assigned by robotbuilder.
// These sections will be updated in the future when you export to
// Java from RobotBuilder. Do not put any code or make any change in
// the blocks indicating autogenerated code or it will be lost on an
// update. Deleting the comments indicating the section will prevent
// it from being updated in the future.

package org.usfirst.frc157.FRC2019.commands;

import edu.wpi.first.wpilibj.Timer;
import edu.wpi.first.wpilibj.command.Command;

import org.usfirst.frc157.FRC2019.OutriggerTask;
import org.usfirst.frc157.FRC2019.Robot;
import org.usfirst.frc157.FRC2019.subsystems.FrontOutriggers;

/**
 *
 */
public class Deploy extends Command {
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATION
    // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_DECLARATIONS
    private double frontTarget = 0;
    private int backTarget = 0;
    private int liftTarget = 0;
    private double startTime = 0;


    private enum states {
       raiseRobot, driveRobot, lowerRobot, raiseOutriggers, done
    }
    private states state = states.raiseRobot;
    // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
    public Deploy()
    {
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=CONSTRUCTOR
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=VARIABLE_SETTING
        // BEGIN AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
        System.out.println("constructor");
        requires(Robot.lift);
        requires(Robot.drive);
        //requires(Robot.frontOutriggers);
        //requires(Robot.backOutriggers);

        // END AUTOGENERATED CODE, SOURCE=ROBOTBUILDER ID=REQUIRES
    }

    // Called just before this Command runs the first time
    @Override
    protected void initialize() {
        System.out.println("initialize");

        frontTarget = 0;
        backTarget = 0;

        liftTarget = 0;
    }

    // Called repeatedly when this Command is scheduled to run
    @Override
    protected void execute()
    {
        double frontPos = Robot.frontOutriggers.frontOutrigger.getPosition();
        double backPos = Robot.backOutriggers.backOutrigger.getPosition();

        double liftPos = Robot.lift.encoder.getDistance();
        OutriggerTask front =  new OutriggerTask(frontTarget, 1,1, 1.0);
        OutriggerTask back =  new OutriggerTask(backTarget, 1,1, 1.0);


        switch (state) {
            case raiseRobot:
                frontTarget = -54;
                backTarget = -41;
                if (Math.abs(frontPos-frontTarget)<3 && Math.abs(backPos-backTarget) < 3) {
                    state = states.driveRobot;
                    startTime = Timer.getFPGATimestamp();
                }
                front = new OutriggerTask(frontTarget, 1,1, 1.0);
                back = new OutriggerTask(backTarget, 1,1, 1.0);
                break;
            case driveRobot:
                if (Timer.getFPGATimestamp()-startTime<1.1) {
                    Robot.drive.tankDrive(0.35, 0.35);
                }
                else {
                    state = states.lowerRobot;
                    Robot.drive.tankDrive(0, 0);

                }
                front = new OutriggerTask(frontTarget, 1,1, 1.0);
                back = new OutriggerTask(backTarget, 1,1, 1.0);
                break;
            case lowerRobot:
                frontTarget = -34;
                backTarget = -37;
                if (Math.abs(frontPos-frontTarget)<3 && Math.abs(backPos-backTarget) < 3) {
                    state = states.done;
                }
                front = new OutriggerTask(frontTarget, 1,1, 1.0);
                back = new OutriggerTask(backTarget, 1,1, 1.0);
                front.landing = true;
                back.landing = true;
                break;
            case raiseOutriggers:
                frontTarget = -2;
                backTarget = -2;
                if (Math.abs(frontPos-frontTarget)<3 && Math.abs(backPos-backTarget) < 3) {
                    state = states.done;
                }
                front = new OutriggerTask(frontTarget, 1,1, 1.0);
                back = new OutriggerTask(backTarget, 1,1, 1.0);
                front.landing = true;
                back.landing = true;
                break;
        }
        //Robot.outriggers.move((isA)?(-1):(1));
      //  System.out.println("\n------\n" + value + "\n" + target);
     //   double moveFront = Robot.frontOutriggers.yawFrontPID.pidCalculate(frontTarget, frontPos);
      //  double moveBack = Robot.backOutriggers.yawBackPID.pidCalculate(backTarget, backPos);
        Robot.frontOutriggers.tasks[Robot.frontOutriggers.liftTask]= front;
        Robot.backOutriggers.tasks[Robot.backOutriggers.liftTask]= back;

        Robot.lift.moveLift(1, liftTarget);
    }

    // Make this return true when this Command no longer needs to run execute()
    @Override
    protected boolean isFinished()
    {
        System.out.println(state);
        return (state == states.done);
    }

    // Called once after isFinished returns true
    @Override
    protected void end() {
        Robot.drive.tankDrive(0, 0);
    }

    // Called when another command which requires one or more of the same
    // subsystems is scheduled to run
    @Override
    protected void interrupted() {
    }
}
